### ISSUE TITLE
Release Branches Frozen For Merging | branch:maistra-2.1 branch:releases/2.2.5 branch:releases/2.3.1

### ISSUE THREAD

**Issue by jwendell** [maistra/envoy#176]
While this issue remains open, tide will not merge any PR's targeting the branches mentioned in the PR title.

**Comment by wufanqqfsc** [comment]
@yxun @jwendell  
Excuse me!
Where to report issue or ask questions for this project? 
Seems in the jira we can't find the Project "[OpenShift Service Mesh](https://issues.redhat.com/projects/OSSM/summary)" when trying to create issue login as a normal Redhead user.
