### ISSUE TITLE
codec_impl_test failure on ppc64le

### ISSUE THREAD

**Issue by nailushapotnuru** [maistra/envoy#21]
//test/common/http/http2:codec_impl_test failed with exception:

Description:
`[ RUN      ] Http2CodecImplTestDefaultSettings/Http2CodecImplTest.Invalid103/0
terminate called after throwing an instance of 'Envoy::Http::CodecProtocolException'
  what():  Unexpected 'trailers' with no end stream.`

Environment:
Arch: ppc64le
Os: rhel 7.6
Gcc: 7.3.1

Console Output:
``//test/common/http/http2:codec_impl_test                                 FAILED in 5 out of 5 in 7.6s
  Stats over 5 runs: max = 7.6s, min = 4.0s, avg = 4.8s, dev = 1.4s
  /root/.cache/bazel/_bazel_root/4997a26a7f98cd23ca6abb09e9aabcaf/execroot/envoy/bazel-out/ppc-fastbuild/testlogs/test/common/http/http2/codec_impl_test/shard_1_of_5/test.log
  /root/.cache/bazel/_bazel_root/4997a26a7f98cd23ca6abb09e9aabcaf/execroot/envoy/bazel-out/ppc-fastbuild/testlogs/test/common/http/http2/codec_impl_test/shard_3_of_5/test.log
  /root/.cache/bazel/_bazel_root/4997a26a7f98cd23ca6abb09e9aabcaf/execroot/envoy/bazel-out/ppc-fastbuild/testlogs/test/common/http/http2/codec_impl_test/shard_2_of_5/test.log
  /root/.cache/bazel/_bazel_root/4997a26a7f98cd23ca6abb09e9aabcaf/execroot/envoy/bazel-out/ppc-fastbuild/testlogs/test/common/http/http2/codec_impl_test/shard_4_of_5/test.log
  /root/.cache/bazel/_bazel_root/4997a26a7f98cd23ca6abb09e9aabcaf/execroot/envoy/bazel-out/ppc-fastbuild/testlogs/test/common/http/http2/codec_impl_test/shard_5_of_5/test.log``

Logs:

[shard_1_of_5.log](https://github.com/Maistra/envoy/files/4727923/shard_1_of_5.log)
[shard_2_of_5.log](https://github.com/Maistra/envoy/files/4727918/shard_2_of_5.log)
[shard_3_of_5.log](https://github.com/Maistra/envoy/files/4727919/shard_3_of_5.log)
[shard_4_of_5.log](https://github.com/Maistra/envoy/files/4727921/shard_4_of_5.log)
[shard_5_of_5.log](https://github.com/Maistra/envoy/files/4727922/shard_5_of_5.log)

**Comment by knrc** [comment]
RHEL 8 is required for building proxy, we have seen no failures on RHEL 8 other than with two of the fuzzing tests which we currently believe is a false positive.

**Comment by jwendell** [comment]
Issues for this repository are tracked in Red Hat Jira. Please head to https://issues.redhat.com/browse/OSSM in order to browse or open an issue.
