### ISSUE TITLE
Test failures due to memory leak on using moonjit instead of luajit

### ISSUE THREAD

**Issue by Ryan-Dmello** [maistra/envoy#49]
**Title**: **Test failures due to memory leak on using moonjit instead of luajit**

**Description**:
I recently executed maistra-2.0 tests on ppc64le machine, using Moonjit instead of Luajit. Below are the repository details:
**Repo name**:   https://github.com/Maistra/envoy.git
**branch**:          maistra-2.0

On performing tests execution found that, following tests are failing:

```
//test/extensions/transport_sockets/tls:context_impl_test
//test/extensions/filters/http/lua:wrappers_test
//test/extensions/filters/http/lua:lua_filter_test
//test/extensions/filters/listener/http_inspector:http_inspector_test (edited) 
```

Upon checking in the logs it was observed that the below tests execution are in passing state. However are marked failed due to memory leaks, in test result summary on ppc64le machine:
```
//test/extensions/filters/http/lua:lua_filter_test
//test/extensions/filters/http/lua:wrappers_test
```

I tried to execute above tests on an x86 machine, with Moonjit and saw similar behavior on x86 machine too.

Below are the changes I have done to use Moonjit over Luajit:
```
diff --git a/bazel/foreign_cc/BUILD b/bazel/foreign_cc/BUILD
index 2658b72e8..4b5058a3d 100644
--- a/bazel/foreign_cc/BUILD
+++ b/bazel/foreign_cc/BUILD
@@ -48,7 +48,7 @@ configure_make(
         "//bazel:asan_build": {"ENVOY_CONFIG_ASAN": "1"},
         "//conditions:default": {},
     }),
-    lib_source = "@com_github_luajit_luajit//:all",
+    lib_source = "@com_github_moonjit_moonjit//:all",
     make_commands = [],
     out_include_dir = "include/luajit-2.1",
     static_libraries = [
```

is the above approach correct? If not what is the correct way to replace luajit with moonjit?

**Comment by Ryan-Dmello** [comment]
Test logs:
[http_lua_lua_filter_test.log](https://github.com/maistra/envoy/files/5371226/http_lua_lua_filter_test.log)
[http_lua_wrappers_test.log](https://github.com/maistra/envoy/files/5371227/http_lua_wrappers_test.log)

**Comment by dmitri-d** [comment]
There's already moonjit repository and build defined here: https://github.com/maistra/envoy/blob/maistra-2.0/bazel/repository_locations.bzl#L124, https://github.com/maistra/envoy/blob/maistra-2.0/bazel/repositories.bzl#L793, and https://github.com/maistra/envoy/blob/maistra-2.0/bazel/foreign_cc/BUILD#L61. There's also a config enabling moonjit defined here: https://github.com/maistra/envoy/blob/maistra-2.0/source/extensions/filters/common/lua/BUILD#L19.

Executing `bazel test --config=with_moonjit //test/...` should pick moonjit and do a build with it.

**Comment by jwendell** [comment]
Issues for this repository are tracked in Red Hat Jira. Please head to https://issues.redhat.com/browse/OSSM in order to browse or open an issue.
